before_script:
  - ruby -v
  - which ruby
  - env
  - script/build/test_db_config.sh
  - bundle install

stages:
  - pre
  - test
  - browser

rubocop:
  stage: pre
  tags:
    - core
  script:
    - bundle exec rubocop

coffeelint:
  stage: pre
  tags:
    - core
  script:
    - coffeelint app/

bundle-audit:
  stage: pre
  tags:
    - core
  script:
    - gem install bundler-audit
    - bundle-audit update
    - bundle-audit

job_unit_mysql:
  stage: test
  tags:
    - core
    - mysql
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - rake test:units
    - rake test:controllers
    - rake db:drop

job_unit_postgresql:
  stage: test
  tags:
    - core
    - postgresql
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - rake test:units
    - rake test:controllers
    - rake db:drop

job_integration_email_helper:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/email_helper_test.rb
    - rake db:drop

job_integration_twitter:
  stage: test
  tags:
    - core
    - twitter
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - ruby -I test/ test/integration/twitter_test.rb
    - rake db:drop
  allow_failure: true

job_integration_facebook:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - ruby -I test/ test/integration/facebook_test.rb
    - rake db:drop
  allow_failure: true

job_integration_geo_ip:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_ip_test.rb
    - rake db:drop

job_integration_geo_location:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_location_test.rb
    - rake db:drop

job_integration_geo_calendar:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_calendar_test.rb
    - rake db:drop

job_integration_user_agent:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/user_agent_test.rb
    - rake db:drop

job_integration_slack:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - echo "gem 'slack-api'" >> Gemfile.local
    - bundle install
    - ruby -I test test/integration/slack_test.rb
    - rake db:drop

job_integration_es_mysql:
  stage: test
  tags:
    - core
    - mysql
  script:
    - export RAILS_ENV=test
    - export ES_INDEX_RAND=true
    - export ES_URL="http://localhost:9200"
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/elasticsearch_test.rb
    - ruby -I test/ test/controllers/search_controller_test.rb
    - ruby -I test/ test/integration/report_test.rb
    - rake db:drop

job_integration_es_postgresql:
  stage: test
  tags:
    - core
    - postgresql
  script:
    - export RAILS_ENV=test
    - export ES_INDEX_RAND=true
    - export ES_URL="http://localhost:9200"
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/elasticsearch_test.rb
    - ruby -I test/ test/controllers/search_controller_test.rb
    - ruby -I test/ test/integration/report_test.rb
    - rake db:drop

job_integration_zendesk_mysql:
  stage: test
  tags:
    - core
    - mysql
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/zendesk_import_test.rb
    - rake db:drop

job_integration_zendesk_postgresql:
  stage: test
  tags:
    - core
    - postgresql
  script:
    - export RAILS_ENV=test
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/zendesk_import_test.rb
    - rake db:drop

job_integration_otrs_5_mysql:
  stage: test
  tags:
    - core
    - mysql
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz599.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb
    - rake db:drop

job_integration_otrs_5_postgresql:
  stage: test
  tags:
    - core
    - postgresql
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz599.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb
    - rake db:drop

job_integration_otrs_4:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz383.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb
    - rake db:drop

job_integration_otrs_33:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz305.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb
    - rake db:drop

job_integration_otrs_32:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz382.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb
    - rake db:drop

job_integration_otrs_31:
  stage: test
  tags:
    - core
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz381.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb
    - rake db:drop

job_integration_twitter_ff:
  stage: browser
  tags:
    - browser-ff
    - twitter
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - RAILS_ENV=test rake db:create
    - cp contrib/auto_wizard_test.json auto_wizard.json
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - ruby -I test/ test/integration/twitter_browser_test.rb || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_facebook_ff:
  stage: browser
  tags:
    - browser-ff
    - facebook
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - RAILS_ENV=test rake db:create
    - cp contrib/auto_wizard_test.json auto_wizard.json
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - ruby -I test/ test/integration/facebook_browser_test.rb || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_autowizard_ff:
  stage: browser
  tags:
    - browser-ff
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - RAILS_ENV=test rake db:create
    - cp contrib/auto_wizard_example.json auto_wizard.json
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - ruby -I test/ test/integration/auto_wizard_test.rb || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_ff_1_mysql:
  stage: browser
  tags:
    - browser-ff
    - mysql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 1
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_ff_2_mysql:
  stage: browser
  tags:
    - browser-ff
    - mysql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 2
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_ff_3_mysql:
  stage: browser
  tags:
    - browser-ff
    - mysql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - script/build/test_slice_tests.sh 3
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_ff_1_postgresql:
  stage: browser
  tags:
    - browser-ff
    - postgresql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 1
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_ff_2_postgresql:
  stage: browser
  tags:
    - browser-ff
    - postgresql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 2
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_ff_3_postgresql:
  stage: browser
  tags:
    - browser-ff
    - postgresql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - script/build/test_slice_tests.sh 3
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_chrome_1_mysql:
  stage: browser
  tags:
    - browser-chrome
    - mysql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 1
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_chrome_2_mysql:
  stage: browser
  tags:
    - browser-chrome
    - mysql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 2
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_chrome_3_mysql:
  stage: browser
  tags:
    - browser-chrome
    - mysql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 3
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_chrome_1_postgresql:
  stage: browser
  tags:
    - browser-chrome
    - postgresql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 1
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_chrome_2_postgresql:
  stage: browser
  tags:
    - browser-chrome
    - postgresql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 2
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_browser_chrome_3_postgresql:
  stage: browser
  tags:
    - browser-chrome
    - postgresql
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 3
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_twitter_chrome:
  stage: browser
  tags:
    - browser-chrome
    - twitter
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - RAILS_ENV=test rake db:create
    - cp contrib/auto_wizard_test.json auto_wizard.json
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - ruby -I test/ test/integration/twitter_browser_test.rb || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_facebook_chrome:
  stage: browser
  tags:
    - browser-chrome
    - facebook
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - RAILS_ENV=test rake db:create
    - cp contrib/auto_wizard_test.json auto_wizard.json
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - ruby -I test/ test/integration/facebook_browser_test.rb || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_otrs_chrome:
  stage: browser
  tags:
    - browser-chrome
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - ruby -I test/ test/integration/otrs_import_browser_test.rb || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_autowizard_chrome:
  stage: browser
  tags:
    - browser-chrome
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - RAILS_ENV=test rake db:create
    - cp contrib/auto_wizard_example.json auto_wizard.json
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - ruby -I test/ test/integration/auto_wizard_test.rb || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT

job_integration_zendesk_chrome:
  stage: browser
  tags:
    - browser-chrome
  script:
    - export BROWSER_URL=http://$IP:$BROWSER_PORT
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
    - ruby -I test/ test/integration/zendesk_import_browser_test.rb || script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT 1
    - script/build/test_shutdown.sh $RAILS_ENV $BROWSER_PORT $WS_PORT
