before_script:
  - ruby -v
  - which ruby
  - env
  - test -n "$RNAME" && script/build/test_db_config.sh
  - test -n "$RNAME" && bundle install

stages:
  - pre

pre:rubocop:
  stage: pre
  tags:
    - core
  script:
    - bundle exec rubocop

pre:coffeelint:
  stage: pre
  tags:
    - core
  script:
    - coffeelint app/

pre:bundle-audit:
  stage: pre
  tags:
    - core
  script:
    - gem install bundler-audit
    - bundle-audit update
    - bundle-audit

pre:github:
  stage: pre
  tags:
    - deploy
  script:
    - script/build/sync_repo.sh git@github.com:zammad/zammad.git

