before_script:
  - bundle install

stages:
  - test

job_unit:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh ci_zammad_unit
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - rake test:units
    - rake test:controllers

job_integration_email_helper:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh ci_zammad_email_helper
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/email_helper_test.rb

job_integration_geo_ip:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh ci_zammad_geo_ip
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_ip_test.rb

job_integration_geo_location:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh ci_zammad_geo_location
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_location_test.rb

job_integration_geo_calendar:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh ci_zammad_geo_calendar
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_calendar_test.rb

job_integration_user_agent:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh ci_zammad_user_agent
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/user_agent_test.rb

rubocop:
  stage: test
  script:
    - bundle exec rubocop
