before_script:
  - bundle install
  - script/build/test_db_config.sh

stages:
  - pre
  - test
  - browser

rubocop:
  stage: pre
  tags:
    - zammad
  script:
    - bundle exec rubocop

coffeelint:
  stage: pre
  tags:
    - zammad
  script:
    - coffeelint app/

job_unit:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - rake test:units
    - rake test:controllers

job_integration_email_helper:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/email_helper_test.rb

job_integration_geo_ip:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_ip_test.rb

job_integration_geo_location:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_location_test.rb

job_integration_geo_calendar:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_calendar_test.rb

job_integration_user_agent:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/user_agent_test.rb

job_integration_es:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/elasticsearch_test.rb
    - ruby -I test/ test/controllers/search_controller_test.rb
    - ruby -I test/ test/integration/report_test.rb

job_integration_otrs_5:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz599.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb

job_integration_otrs_4:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz383.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb

job_integration_otrs_33:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz305.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb

job_integration_otrs_32:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz382.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb

job_integration_otrs_31:
  stage: test
  tags:
    - zammad
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz381.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb

job_integration_autowizard_ff:
  stage: browser
  tags:
    - browser-ff
  script:
    - export BROWSER_URL=http://$IP:3001
    - RAILS_ENV=test rake db:create
    - cp contrib/auto_wizard_example.json auto_wizard.json
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV 3001 3002
    - ruby -I test/ test/integration/auto_wizard_test.rb || script/build/test_shutdown.sh $RAILS_ENV 3011 3012 1
    - script/build/test_shutdown.sh $RAILS_ENV 3001 3002

job_integration_browser_ff_1:
  stage: browser
  tags:
    - browser-ff
  script:
    - export BROWSER_URL=http://$IP:3011
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 1
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV 3011 3012
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV 3011 3012 1
    - script/build/test_shutdown.sh $RAILS_ENV 3011 3012

job_integration_browser_ff_2:
  stage: browser
  tags:
    - browser-ff
  script:
    - export BROWSER_URL=http://$IP:3021
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 2
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV 3021 3022
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV 3021 3022 1
    - script/build/test_shutdown.sh $RAILS_ENV 3021 3022

job_integration_browser_ff_3:
  stage: browser
  tags:
    - browser-ff
  script:
    - export BROWSER_URL=http://$IP:3031
    - script/build/test_slice_tests.sh 3
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV 3031 3032
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV 3031 3032 1
    - script/build/test_shutdown.sh $RAILS_ENV 3031 3032

job_integration_autowizard_chrome:
  stage: browser
  tags:
    - browser-chrome
  script:
    - export BROWSER_URL=http://$IP:3071
    - RAILS_ENV=test rake db:create
    - cp contrib/auto_wizard_example.json auto_wizard.json
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV 3071 3072
    - ruby -I test/ test/integration/auto_wizard_test.rb || script/build/test_shutdown.sh $RAILS_ENV 3071 3072 1
    - script/build/test_shutdown.sh $RAILS_ENV 3071 3072

job_integration_browser_chrome_1:
  stage: browser
  tags:
    - browser-chrome
  script:
    - export BROWSER_URL=http://$IP:3041
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 1
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV 3041 3042
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV 3041 3042 1
    - script/build/test_shutdown.sh $RAILS_ENV 3041 3042

job_integration_browser_chrome_2:
  stage: browser
  tags:
    - browser-chrome
  script:
    - export BROWSER_URL=http://$IP:3051
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 2
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV 3051 3052
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV 3051 3052 1
    - script/build/test_shutdown.sh $RAILS_ENV 3051 3052

job_integration_browser_chrome_3:
  stage: browser
  tags:
    - browser-chrome
  script:
    - export BROWSER_URL=http://$IP:3061
    - unset MAILBOX_AUTO1
    - unset MAILBOX_AUTO2
    - unset MAILBOX_MANUAL1
    - unset MAILBOX_MANUAL2
    - script/build/test_slice_tests.sh 3
    - RAILS_ENV=test rake db:create
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV 3061 3062
    - rake test:browser || script/build/test_shutdown.sh $RAILS_ENV 3061 3062 1
    - script/build/test_shutdown.sh $RAILS_ENV 3061 3062
