targets:
  centos-6:
    dependencies:
      - httpd
      - mysql-server

user: "zammad"
group: "zammad"

after_install: packaging/hooks/postinstall.sh

before:
  - cp config/database.yml.unittest config/database.yml
  - cat config/database.yml
  - env

env:
  - RAILS_ENV=production
  - RAILS_GROUPS=assets

notifications: false

