name: zammad
description: Zammad is a web based open source helpdesk/customer support system
homepage: https://zammad.org
notifications: false
targets:
  centos-7:
    dependencies:
      - nginx
      - postgresql-server
  debian-8:
    dependencies:
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
  ubuntu-16.04:
    dependencies:
      - nginx|apache2
      - postgresql|mysql-server|mariadb-server|sqlite
  sles-12:
    dependencies:
      - nginx
      - postgresql-server
before:
  - uname -a
  - ruby -v
  - env
  - "cat Gemfile.lock"
  - contrib/cleanup.sh
env:
  - RAILS_ENV=production
  - PORT=3000
services:
  - postgres
after:
  - curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/monotek/zammad/trigger/673cdf9b-dd8d-4f34-b8f2-ad808d9aa83b/
after_install: contrib/packager.io/postinstall.sh
