targets:
  centos-6:
    dependencies:
      - httpd
      - postgresql
      - postgresql-server
      - postgresql-devel
  centos-7:
    dependencies:
      - httpd
      - postgresql
      - postgresql-server
      - postgresql-devel
  debian-7:
    dependencies:
      - nginx
      - postgresql
  ubuntu-16.04:
    dependencies:
      - nginx
      - postgresql
    after_install:
      - zammad scale web=1 websocket=1 worker=1
      - systemctl restart zammad
      - /opt/zammad/contrib/nginx/sites-available/zammad.conf /etc/nginx/sites-available/zammad.conf
      - ln -s /etc/nginx/sites-available/zammad.conf /etc/nginx/sites-enabled/zammad.conf
      - sytemctl restart nginx
before:
  - uname -a
  - ruby -v
  - env
  - cp config/database.yml.pkgr config/database.yml
  - echo "gem 'mysql2'" >> Gemfile.local
  - "cat Gemfile.lock"
  - contrib/cleanup.sh

env:
  - RAILS_ENV=production
  - PORT=3000
  - RAILS_SERVE_STATIC_FILES=true

services:
  - postgres

notifications: false
