targets:
  centos-6:
    dependencies:
      - httpd
      - mysql-server

user: "zammad"
group: "zammad"

after_install: packaging/hooks/postinstall.sh

before_precompile:
  - cp config/database.yml.unittest config/database.yml

after_precompile:
  - rm -f config/database.yml

env:
  - RAILS_ENV=production
  - RAILS_GROUPS=assets

notifications: false

