targets:
  centos-6:
    dependencies:
      - httpd
      - mysql-server

user: "zammad"
group: "zammad"

after_install: packaging/hooks/postinstall.sh

env:
  - RAILS_ENV=production
  - RAILS_GROUPS=assets

notifications: false

