notifications: false

targets:
  centos-6:
    dependencies:
      - httpd
      - postgresql
      - postgresql-server
      - postgresql-devel
  centos-7:
    dependencies:
      - httpd
      - postgresql
      - postgresql-server
      - postgresql-devel
  debian-8:
    dependencies:
      - nginx
      - postgresql
  ubuntu-16.04:
    dependencies:
      - nginx
      - postgresql

before:
  - uname -a
  - ruby -v
  - env
  - cp config/database.yml.pkgr config/database.yml
  - echo "gem 'mysql2'" >> Gemfile.local
  - "cat Gemfile.lock"
  - contrib/cleanup.sh

env:
  - RAILS_ENV=production
  - PORT=3000
  - RAILS_SERVE_STATIC_FILES=true

services:
  - postgres

after_install:
  - "/usr/bin/zammad scale web=1 websocket=1 worker=1"
