name: ci

on: 
  pull_request:

jobs:
  lint-bash-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint Bash scripts
        uses: docker://koalaman/shellcheck-alpine:v0.7.0
        with:
          args: .github/lint-scripts.sh

  ci:
    runs-on: ubuntu-latest
    needs: lint-scripts
    strategy:
      matrix:
        dbs:
          - mysql
          - postgresql
    env: 
      ZAMMAD_DBS: ${{ matrix.dbs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: CI  
        run: .github/ci.sh
